site_name: EDU Project
site_author: Thibault de Saint Sernin
theme:
    name: 'material'
    palette:
        primary: 'cyan'
        accent: 'cyan'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
    feature:
        tabs: true

repo_name: 'Thibault2ss/edu'
repo_url: 'https://github.com/Thibault2ss/edu'

extra:
    social:
        - type: 'github'
          link: 'https://github.com/Thibault2ss/edu'
        - type: 'twitter'
          link: ''
        - type: 'linkedin'
          link: ''

copyright: 'Copyright &copy; 2016 - 2018 Thibault de Saint Sernin'

markdown_extensions:
    - admonition
    - toc:
        permalink: true
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
